lib/catcasts_web/router.ex
defmodule CatcastsWeb.Router do
  use CatcastsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Catcasts.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug CatcastsWeb.Plugs.RequireAuth
  end

  scope "/", CatcastsWeb do
    pipe_through [:browser, :auth]

    resources "/videos", VideoController, only: [:new, :create, :delete]
  end

  scope "/", CatcastsWeb do
    pipe_through :browser

    resources "/videos", VideoController, only: [:index, :show]
    get "/", PageController, :index
  end

  scope "/auth", CatcastsWeb do
    pipe_through :browser

    get "/signout", SessionController, :delete
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :create
  end
end

lib/catcasts_web/views/layout_view.ex
defmodule CatcastsWeb.LayoutView do
  use CatcastsWeb, :view
end

lib/catcasts_web/templates/layout/_navigation.html.eex
<nav class="flex items-center justify-between flex-wrap bg-grey-lightest p-3 font-sans">
  <div class="flex items-center flex-no-shrink text-grey-darkest mr-6">
    <span class="font-semibold text-xl tracking-tight">Catcasts</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-grey-darkest border-grey-darkest" onclick="navbarAccordian()">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto" id="nav">
    <div class="text-sm lg:flex-grow">
    </div>
    <div>
            
      <%= if @conn.assigns[:user] do %>
        <span class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
          Welcome, <%= @conn.assigns.user.first_name %>!
        </span>
        <%= link "Videos", to: Routes.video_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
        <%= link "Add video", to: Routes.video_path(@conn, :new), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
        <%= link "Sign out", to: Routes.session_path(@conn, :delete), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
      <% else %>
        <%= link "Videos", to: Routes.video_path(@conn, :index), class: "block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline" %>
        <a href="/auth/google?scope=email%20profile" class="block mt-4 lg:inline-block lg:mt-0 text-grey-darkest mr-4 no-underline hover:underline">
          Sign in with Google
        </a>
      <% end %>
        
        
    </div>
  </div>
  <script>
    function navbarAccordian() {
    var x = document.getElementById("nav");
    x.classList.toggle("hidden");
    }
  </script>
</nav>

lib/catcasts_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Catcasts · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "_navigation.html", conn: @conn%>
    <main role="main">
    <p class="alert bg-blue-lightest border border-blue-light text-blue-dark px-4 py-3 rounded relative" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert bg-red-lightest border border-red-light text-red-dark px-4 py-3 rounded relative" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>